export enum RoomMessage {
  CreateRoom = "create-room",
  ChangeClient = "change-client",
  ExecuteRoom = "execute-room",
  ConnectRoom = "connect-room",
  RoomQuestionnaire = "room-questionnaire",
  Editor = "editor",
  RoomChangeLanguage = "room-change-language",
  EditorSelection = "editor-selection",
  EditorState = "editor-state",
  RoomAddClient = "room-add-client",
  RoomRemoveClient = "room-remove-client",
  RoomChangeClient = "room-change-client",
  RoomStartCode = "room-start-code",
  RoomEndCode = "room-end-code",
  RoomEndCodeData = "room-end-code-data",
  RoomEndCodeErr = "room-end-code-err",
  RoomUpdateClients = "room-update-clients",
}
